"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-OpenServ',
 'project_name': 'OpenImpact Dispatcher',
 'track': 'OpenServ',
 'pitch': 'A load-bearing service fabric for discovery, scheduling, execution '
          'receipts, and build-story outputs across the whole swarm.',
 'idea_titles': ['Autonomous Public-Goods Dispatch',
                 'x402 Agentic Service Hub',
                 'ERC-8004-backed DeFi Ops Queue'],
 'architecture_summary': 'A coordinator exposes load-bearing service interfaces for '
                         'discovery, scheduling, execution receipts, and build-story '
                         'outputs. The contract layer stores job policies and '
                         'completion receipts while Python workers route tasks to '
                         'track-specific adapters.',
 'overlap_targets': ['Octant',
                     'Filecoin',
                     'ERC-8004 Receipts',
                     'Olas',
                     'Uniswap Agentic Finance',
                     'Markee'],
 'primary_contract_name': 'OpenServJobBoard',
 'primary_python_module': 'openimpact_dispatcher',
 'category': 'orchestration',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'problem_signal',
                       'description': 'Discovery inputs used to detect a real '
                                      'opportunity.'},
                      {'name': 'policy_envelope',
                       'description': 'Budget, caps, and cooldown policy state.'},
                      {'name': 'execution_bundle',
                       'description': 'Dry-run and live execution bundle metadata.'},
                      {'name': 'receipts',
                       'description': 'Submission notes and final verification '
                                      'digests.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for OpenServJobBoard.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'openimpact_dispatcher.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'OpenServ',
               'docs_url': 'https://docs.openserv.ai/',
               'env_vars': ['OPENSERV_API_KEY', 'OPENSERV_AGENT_URL'],
               'endpoint_env': 'OPENSERV_AGENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Dispatch jobs and expose swarm service endpoints.'},
              {'name': 'Octant',
               'docs_url': 'https://octant.app/',
               'env_vars': ['OCTANT_SIGNAL_URL'],
               'endpoint_env': 'OCTANT_SIGNAL_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish scored public-goods signals and DPI artifacts.'},
              {'name': 'Filecoin',
               'docs_url': 'https://docs.filecoin.cloud/',
               'env_vars': ['FILECOIN_API_TOKEN', 'FILECOIN_UPLOAD_URL'],
               'endpoint_env': 'FILECOIN_UPLOAD_URL',
               'action_kind': 'file_upload',
               'purpose': 'Persist proofs, logs, and evidence bundles offchain.'},
              {'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'},
              {'name': 'Olas',
               'docs_url': 'https://docs.olas.network/',
               'env_vars': ['OLAS_API_KEY', 'OLAS_REQUEST_URL'],
               'endpoint_env': 'OLAS_REQUEST_URL',
               'action_kind': 'rest_json',
               'purpose': 'Hire and serve marketplace requests with receipts.'},
              {'name': 'Uniswap',
               'docs_url': 'https://developers.uniswap.org/',
               'env_vars': ['UNISWAP_API_KEY', 'UNISWAP_QUOTE_URL'],
               'endpoint_env': 'UNISWAP_QUOTE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Quote swaps and bounded liquidity moves.'},
              {'name': 'Markee',
               'docs_url': 'https://markee.xyz/',
               'env_vars': ['MARKEE_API_KEY', 'MARKEE_MESSAGE_URL'],
               'endpoint_env': 'MARKEE_MESSAGE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish GitHub-adjacent build stories and repo messages.'}],
 'actions': [{'id': 'openserv_job_dispatch',
              'target': 'openserv',
              'purpose': 'Use OpenServ for a bounded action in this repo.',
              'partner': 'OpenServ',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call OpenServ only after a dry-run artifact exists.',
                        'Use https://docs.openserv.ai/ for credential setup.']},
             {'id': 'octant_signal_publish',
              'target': 'octant',
              'purpose': 'Use Octant for a bounded action in this repo.',
              'partner': 'Octant',
              'action_kind': 'rest_json',
              'max_amount_usd': 25,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call Octant only after a dry-run artifact exists.',
                        'Use https://octant.app/ for credential setup.']},
             {'id': 'filecoin_proof_store',
              'target': 'filecoin',
              'purpose': 'Use Filecoin for a bounded action in this repo.',
              'partner': 'Filecoin',
              'action_kind': 'file_upload',
              'max_amount_usd': 20,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call Filecoin only after a dry-run artifact exists.',
                        'Use https://docs.filecoin.cloud/ for credential setup.']},
             {'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 85,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']},
             {'id': 'olas_market_hire',
              'target': 'olas',
              'purpose': 'Use Olas for a bounded action in this repo.',
              'partner': 'Olas',
              'action_kind': 'rest_json',
              'max_amount_usd': 20,
              'priority': 80,
              'sensitivity': 'medium',
              'notes': ['Call Olas only after a dry-run artifact exists.',
                        'Use https://docs.olas.network/ for credential setup.']},
             {'id': 'uniswap_quote_route',
              'target': 'uniswap',
              'purpose': 'Use Uniswap for a bounded action in this repo.',
              'partner': 'Uniswap',
              'action_kind': 'rest_json',
              'max_amount_usd': 220,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call Uniswap only after a dry-run artifact exists.',
                        'Use https://developers.uniswap.org/ for credential setup.']},
             {'id': 'markee_repo_message',
              'target': 'markee',
              'purpose': 'Use Markee for a bounded action in this repo.',
              'partner': 'Markee',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 70,
              'sensitivity': 'low',
              'notes': ['Call Markee only after a dry-run artifact exists.',
                        'Use https://markee.xyz/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
